#!/bin/sh
set -e -u

#*************************************************************************
#*************************************************************************
OSMOSIS_BIN=osmosis
OSM2PGSQL_BIN=osm2pgsql
OSM2PGSQL_OPTIONS="-S /home/zverik/veloroad/veloroad.style"
#OSM2PGSQL_OPTIONS="--flat-nodes /path/to/flatnodes --hstore"

BASE_DIR="$(dirname "$0")"
WORKOSM_DIR=$BASE_DIR/osmosis
CHANGE_FILE=$BASE_DIR/changes.osc.gz
RUNLOG=$BASE_DIR/openstreetmap_update.log

TRIM_OSC=/home/zverik/trim_osc.py
TRIM_POLY="$BASE_DIR/grozny-big.poly"

#*************************************************************************
#*************************************************************************

m_info()
{
        echo "[`date +"%Y-%m-%d %H:%M:%S"`] $$ $1" >> "$RUNLOG"
}

m_error()
{
    echo "[`date +"%Y-%m-%d %H:%M:%S"`] $$ [error] $1" >> "$RUNLOG"
    
    m_info "resetting state"
    cp $WORKOSM_DIR/last.state.txt $WORKOSM_DIR/state.txt || true
    
    rm "$CHANGE_FILE" || true
    exit
}

m_ok()
{
    echo "[`date +"%Y-%m-%d %H:%M:%S"`] $$ $1" >> "$RUNLOG"
}

if [ $# -eq 1 ] ; then
    m_info "Initialising Osmosis replication system to $1"
    mkdir $WORKOSM_DIR
    $OSMOSIS_BIN --read-replication-interval-init workingDirectory=$WORKOSM_DIR 1>&2 2> "$RUNLOG"
    wget "$1" -O $WORKOSM_DIR/state.txt
else
    [ ! -f "$WORKOSM_DIR/state.txt" ] && echo "Run this script with 000.txt URL" && exit 1

    seq=`cat $WORKOSM_DIR/state.txt | grep sequenceNumber | cut -d= -f2`

    m_ok "start import from seq-nr $seq"

    cp $WORKOSM_DIR/state.txt $WORKOSM_DIR/last.state.txt
    m_ok "downloading diff"
    
    if ! $OSMOSIS_BIN --read-replication-interval workingDirectory=$WORKOSM_DIR --simplify-change --write-xml-change $CHANGE_FILE 1>&2 2>> "$RUNLOG"; then
        m_error "Osmosis error"
    fi

    if [ -n "$TRIM_OSC" ]; then
    m_ok "filtering diff"
    if ! "$TRIM_OSC" -v -d gis -p "$TRIM_POLY" -z $CHANGE_FILE $CHANGE_FILE 1>&2 2>> "$RUNLOG"; then
	m_error "Trim_osc error"
    fi
    fi
    
    m_ok "importing diff"
    if ! $OSM2PGSQL_BIN -a --slim $OSM2PGSQL_OPTIONS $CHANGE_FILE 1>&2 2> /dev/null; then
        m_error "osm2pgsql error"
    fi
    rm "$CHANGE_FILE"

    m_ok "Done with import"
fi
